apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-labels
  labels:
    environtment: production
    version: 1.1.2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
